# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_secret', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='like',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
